apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "cat /opt/app.properties" ]
      volumeMounts:
      - name: config-volume
        mountPath: /opt
  volumes:
    - name: config-volume
      configMap:
        name: app-config
  restartPolicy: Never
