apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  externalIPs:
  - 34.93.51.74 
  - 35.200.224.0 
## for  GKE
## kubectl port-forward svc/nginx-service 8888:80
## curl localhost:8888
